baseURL: "https://askan.me"
languageCode: "en-us"
title: "Yigit's Blog"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "https://twitter.com/yig_do"
  github: "#"
  instagram: "https://instagram.com/yig.do"
  linkedin: "https://linkedin.com/in/yigitaskan"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
